  Breeefind#2[m
  Breeefing[m
  DashHandlowie[m
  Kalendarz[m
  Mapowanie[m
  Menu[m
  Menu-ciąg-dalszy[m
  Mroznia2[m
  Mroźnia[m
  Opakowania[m
  PDF-AVilog[m
  PanelAdminCRM[m
  PlanTygodniowy[m
  PlanowanyPrzychod[m
  Produkcja-plan[m
  SMS[m
  Specki[m
  Specki-i-matryca[m
  SpeckiMapowanieIiNNe[m
  Sprzedaz-dodatkowe-kolumny[m
  Sprzedazz[m
  Sprzedaż[m
* [32mTest1[m
  Wstawienia[m
  Zywiec-avatary[m
  Zywiec4[m
  claude/add-cameras-view-mode-TqWhO[m
  claude/add-container-pdf-generation-B2GmT[m
  claude/add-context-menu-NoPFE[m
  claude/add-pdf-generator-containers-uRQWU[m
  claude/crm-manager-pro-wpf-aWTUY[m
  claude/dark-corporate-theme-6tdfg[m
  claude/email-pdf-specification-HPYml[m
  claude/fix-csv-export-irzplus-QgVQ1[m
  claude/fix-merged-code-errors-VI6PY[m
  claude/fix-staticresource-reference-KiDPu[m
  claude/meeting-notifications-system-8Pgpx[m
  claude/offer-without-recipient-014Ke5boxBrsK2A6p5vBXrxu[m
  claude/review-crm-menu-tile-01TMjAP459P2gTqQQLdMGB4X[m
  claude/setup-zpsp-system-uNWLo[m
  master[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/Test1[m
  [31mremotes/origin/claude/add-cameras-view-mode-TqWhO[m
  [31mremotes/origin/claude/add-comparison-section-pMNhr[m
  [31mremotes/origin/claude/add-container-pdf-generation-B2GmT[m
  [31mremotes/origin/claude/add-context-menu-NoPFE[m
  [31mremotes/origin/claude/add-daily-summary-menu-01XH83vvnZXPS1gKKMe1cUrx[m
  [31mremotes/origin/claude/add-monitoring-tile-01L7DCVr6XpushxMnyJAyc24[m
  [31mremotes/origin/claude/add-pdf-generator-containers-uRQWU[m
  [31mremotes/origin/claude/add-product-group-columns-01NqJiAbJkSzwYmars1Yajw7[m
  [31mremotes/origin/claude/add-production-summary-11wjU[m
  [31mremotes/origin/claude/add-supplier-mapping-pDw8c[m
  [31mremotes/origin/claude/analyze-calendar-wpf-RQ7iv[m
  [31mremotes/origin/claude/analyze-chicken-program-ueaz9[m
  [31mremotes/origin/claude/analyze-supply-menu-HOzIH[m
  [31mremotes/origin/claude/analyze-supply-shopping-xc9ik[m
  [31mremotes/origin/claude/android-mobile-app-uRx1D[m
  [31mremotes/origin/claude/complaint-details-image-01P1jyt2nj7Dpy2zfr2kdH2p[m
  [31mremotes/origin/claude/crm-callback-notifications-f1Oa2[m
  [31mremotes/origin/claude/crm-manager-pro-wpf-aWTUY[m
  [31mremotes/origin/claude/customer-database-module-x8B75[m
  [31mremotes/origin/claude/dark-corporate-theme-6tdfg[m
  [31mremotes/origin/claude/dynamic-revenue-dashboard-px4U5[m
  [31mremotes/origin/claude/email-pdf-specification-HPYml[m
  [31mremotes/origin/claude/excel-import-transport-N1dJA[m
  [31mremotes/origin/claude/expand-admin-panel-dmXFK[m
  [31mremotes/origin/claude/fix-border-background-error-QAy18[m
  [31mremotes/origin/claude/fix-context-menu-click-1FItv[m
  [31mremotes/origin/claude/fix-csv-export-irzplus-QgVQ1[m
  [31mremotes/origin/claude/fix-frozen-product-category-011yQikLX7YhjYKJ8YKH2GXM[m
  [31mremotes/origin/claude/fix-merge-conflict-5Vjw6[m
  [31mremotes/origin/claude/fix-merged-code-errors-VI6PY[m
  [31mremotes/origin/claude/fix-spec-pdf-colors-F8x3n[m
  [31mremotes/origin/claude/fix-spec-print-error-ghzam[m
  [31mremotes/origin/claude/fix-staticresource-reference-KiDPu[m
  [31mremotes/origin/claude/improve-merchant-dashboard-01V8CRe8Fia1oWkEavctC4Q4[m
  [31mremotes/origin/claude/improve-pdf-import-P1Vj1[m
  [31mremotes/origin/claude/improve-test-coverage-bcDGM[m
  [31mremotes/origin/claude/lazy-load-order-cards-fItls[m
  [31mremotes/origin/claude/market-intelligence-dashboard-2bHRg[m
  [31mremotes/origin/claude/meeting-notifications-system-8Pgpx[m
  [31mremotes/origin/claude/merchant-price-analysis-01V5omQgkdNXEsEGMbvKRfD2[m
  [31mremotes/origin/claude/mobile-order-management-app-f89Sr[m
  [31mremotes/origin/claude/modify-menu-system-dALHi[m
  [31mremotes/origin/claude/multi-window-menu-hFqsZ[m
  [31mremotes/origin/claude/offer-without-recipient-014Ke5boxBrsK2A6p5vBXrxu[m
  [31mremotes/origin/claude/optimize-wpf-dashboard-QbwGr[m
  [31mremotes/origin/claude/order-change-detection-01HkdD3Xaqr55A4VpM4fS57v[m
  [31mremotes/origin/claude/poultry-business-setup-4hLgf[m
  [31mremotes/origin/claude/poultry-revenue-dashboard-clS6T[m
  [31mremotes/origin/claude/refactor-zpsp-sales-PaVnQ[m
  [31mremotes/origin/claude/returnable-packaging-module-XFY56[m
  [31mremotes/origin/claude/review-crm-menu-tile-01TMjAP459P2gTqQQLdMGB4X[m
  [31mremotes/origin/claude/review-mroznia-panel-WZygr[m
  [31mremotes/origin/claude/setup-zpsp-system-uNWLo[m
  [31mremotes/origin/claude/sms-sales-notifications-TzCy3[m
  [31mremotes/origin/claude/teams-integration-analysis-dNsFV[m
  [31mremotes/origin/claude/transport-driver-vehicle-assignment-0156YHJvbG3Tvg3hydSp1ont[m
  [31mremotes/origin/master[m
  [31mremotes/origin/test/devexpress[m
