using System;
using System.Collections.Generic;

namespace Kalendarz1
{
    /// <summary>
    /// Manager imienin - przechowuje polskie imieniny na każdy dzień roku
    /// </summary>
    public static class NameDaysManager
    {
        // Słownik imienin: klucz = "MM-dd", wartość = lista imion
        private static readonly Dictionary<string, string[]> NameDays = new Dictionary<string, string[]>
        {
            // Styczeń
            ["01-01"] = new[] { "Mieczysław", "Mieszko", "Mieczysława" },
            ["01-02"] = new[] { "Izydor", "Grzegorz", "Bazyli" },
            ["01-03"] = new[] { "Genowefa", "Danuta", "Arnold" },
            ["01-04"] = new[] { "Tytus", "Anzelm", "Eugeniusz" },
            ["01-05"] = new[] { "Edward", "Hanna", "Szymon" },
            ["01-06"] = new[] { "Kacper", "Melchior", "Baltazar" },
            ["01-07"] = new[] { "Lucjan", "Julian", "Walenty" },
            ["01-08"] = new[] { "Seweryn", "Mścisław", "Juliusz" },
            ["01-09"] = new[] { "Adrian", "Marcjanna", "Julianna" },
            ["01-10"] = new[] { "Wilhelm", "Dobrosław", "Danuta" },
            ["01-11"] = new[] { "Matylda", "Honorata", "Teodozjusz" },
            ["01-12"] = new[] { "Arkadiusz", "Gracja", "Benedykt" },
            ["01-13"] = new[] { "Bogumił", "Weronika", "Hilary" },
            ["01-14"] = new[] { "Feliks", "Nina", "Hilarion" },
            ["01-15"] = new[] { "Paweł", "Arnold", "Izydor" },
            ["01-16"] = new[] { "Marceli", "Włodzimierz", "Walerian" },
            ["01-17"] = new[] { "Antoni", "Jan", "Henryk" },
            ["01-18"] = new[] { "Piotr", "Małgorzata", "Beatrycze" },
            ["01-19"] = new[] { "Henryk", "Mariusz", "Marta" },
            ["01-20"] = new[] { "Fabian", "Sebastian", "Dobiegniew" },
            ["01-21"] = new[] { "Agnieszka", "Inez", "Jarosław" },
            ["01-22"] = new[] { "Wincenty", "Anastazy", "Gaudencja" },
            ["01-23"] = new[] { "Rajmund", "Ildefons", "Emerencja" },
            ["01-24"] = new[] { "Felicja", "Franciszek", "Rafał" },
            ["01-25"] = new[] { "Paweł", "Miłosz", "Elwira" },
            ["01-26"] = new[] { "Tymoteusz", "Paula", "Michał" },
            ["01-27"] = new[] { "Aniela", "Angelika", "Przybysław" },
            ["01-28"] = new[] { "Tomasz", "Karol", "Waleriusz" },
            ["01-29"] = new[] { "Zdzisław", "Franciszek", "Józef" },
            ["01-30"] = new[] { "Maciej", "Martyna", "Aldona" },
            ["01-31"] = new[] { "Jan", "Marcela", "Ludwika" },

            // Luty
            ["02-01"] = new[] { "Brygida", "Ignacy", "Siemirad" },
            ["02-02"] = new[] { "Maria", "Miłosław", "Korneliusz" },
            ["02-03"] = new[] { "Błażej", "Oskar", "Agata" },
            ["02-04"] = new[] { "Andrzej", "Weronika", "Joanna" },
            ["02-05"] = new[] { "Agata", "Izydora", "Adelajda" },
            ["02-06"] = new[] { "Dorota", "Paweł", "Bogdan" },
            ["02-07"] = new[] { "Ryszard", "Romuald", "Teodor" },
            ["02-08"] = new[] { "Hieronim", "Sebastian", "Honorata" },
            ["02-09"] = new[] { "Apolonia", "Cyryl", "Eryk" },
            ["02-10"] = new[] { "Elwira", "Jacek", "Scholastyka" },
            ["02-11"] = new[] { "Lucjan", "Grzegorz", "Dezydery" },
            ["02-12"] = new[] { "Eulalia", "Julian", "Damian" },
            ["02-13"] = new[] { "Grzegorz", "Katarzyna", "Jordan" },
            ["02-14"] = new[] { "Walenty", "Cyryl", "Metody" },
            ["02-15"] = new[] { "Jowita", "Faustyn", "Zygfryd" },
            ["02-16"] = new[] { "Danuta", "Juliana", "Daniel" },
            ["02-17"] = new[] { "Aleksy", "Zbigniew", "Łukasz" },
            ["02-18"] = new[] { "Konstancja", "Szymon", "Bernadeta" },
            ["02-19"] = new[] { "Arnold", "Konrad", "Józef" },
            ["02-20"] = new[] { "Leon", "Ludomir", "Eucheryk" },
            ["02-21"] = new[] { "Eleonora", "Robert", "Kiejstut" },
            ["02-22"] = new[] { "Marta", "Małgorzata", "Piotr" },
            ["02-23"] = new[] { "Romana", "Damian", "Polikarp" },
            ["02-24"] = new[] { "Maciej", "Bogusz", "Modest" },
            ["02-25"] = new[] { "Cezary", "Wiktor", "Donata" },
            ["02-26"] = new[] { "Aleksander", "Mirosław", "Bogumił" },
            ["02-27"] = new[] { "Gabriel", "Anastazja", "Honoryna" },
            ["02-28"] = new[] { "Roman", "Ludomir", "Makary" },
            ["02-29"] = new[] { "Roman", "Ludomir" }, // Rok przestępny

            // Marzec
            ["03-01"] = new[] { "Albina", "Antoni", "Radosław" },
            ["03-02"] = new[] { "Helena", "Halszka", "Paweł" },
            ["03-03"] = new[] { "Kunegunda", "Maryna", "Tycjan" },
            ["03-04"] = new[] { "Kazimierz", "Łucja", "Eugeniusz" },
            ["03-05"] = new[] { "Adrian", "Fryderyk", "Oliwia" },
            ["03-06"] = new[] { "Róża", "Jordan", "Wiktor" },
            ["03-07"] = new[] { "Tomasz", "Paweł", "Felicyta" },
            ["03-08"] = new[] { "Beata", "Jan", "Stefan" },
            ["03-09"] = new[] { "Franciszka", "Dominik", "Katarzyna" },
            ["03-10"] = new[] { "Cyprian", "Aleksander", "Marceli" },
            ["03-11"] = new[] { "Benedykt", "Konstanty", "Eulogia" },
            ["03-12"] = new[] { "Grzegorz", "Justyna", "Bernard" },
            ["03-13"] = new[] { "Krystyna", "Bożena", "Rodrigo" },
            ["03-14"] = new[] { "Matylda", "Leon", "Łazarz" },
            ["03-15"] = new[] { "Longin", "Klemens", "Ludwika" },
            ["03-16"] = new[] { "Izabela", "Herbert", "Abraham" },
            ["03-17"] = new[] { "Patryk", "Zbigniew", "Gertruda" },
            ["03-18"] = new[] { "Cyryl", "Edward", "Anzelm" },
            ["03-19"] = new[] { "Józef", "Bogdan", "Marek" },
            ["03-20"] = new[] { "Klaudia", "Anatol", "Eufemia" },
            ["03-21"] = new[] { "Benedykt", "Ludomir", "Mikołaj" },
            ["03-22"] = new[] { "Katarzyna", "Bogusław", "Zachariasz" },
            ["03-23"] = new[] { "Pelagia", "Feliks", "Oktawian" },
            ["03-24"] = new[] { "Gabriel", "Marek", "Katarzyna" },
            ["03-25"] = new[] { "Maria", "Wienczysław", "Ireneusz" },
            ["03-26"] = new[] { "Emanuel", "Larysa", "Teodor" },
            ["03-27"] = new[] { "Ernest", "Lidia", "Rupert" },
            ["03-28"] = new[] { "Aniela", "Jan", "Sykstus" },
            ["03-29"] = new[] { "Wiktoryn", "Helmut", "Bertold" },
            ["03-30"] = new[] { "Aniela", "Leonard", "Kwiryn" },
            ["03-31"] = new[] { "Beniamin", "Balbina", "Kornelia" },

            // Kwiecień
            ["04-01"] = new[] { "Grażyna", "Zbigniew", "Teodora" },
            ["04-02"] = new[] { "Franciszek", "Władysław", "Urban" },
            ["04-03"] = new[] { "Ryszard", "Irena", "Pankracy" },
            ["04-04"] = new[] { "Izydor", "Wacław", "Benedykt" },
            ["04-05"] = new[] { "Irena", "Wincenty", "Katarzyna" },
            ["04-06"] = new[] { "Celestyn", "Izolda", "Wilhelm" },
            ["04-07"] = new[] { "Donata", "Rufin", "Herman" },
            ["04-08"] = new[] { "Cezaryna", "Julia", "Dionizy" },
            ["04-09"] = new[] { "Maria", "Marceli", "Hektor" },
            ["04-10"] = new[] { "Michał", "Makary", "Ezechiel" },
            ["04-11"] = new[] { "Leon", "Filip", "Gemma" },
            ["04-12"] = new[] { "Juliusz", "Zenon", "Damian" },
            ["04-13"] = new[] { "Przemysław", "Ida", "Hermenegild" },
            ["04-14"] = new[] { "Berenika", "Walerian", "Justyna" },
            ["04-15"] = new[] { "Anastazja", "Ludwina", "Wacława" },
            ["04-16"] = new[] { "Bernadeta", "Cecylian", "Ksenia" },
            ["04-17"] = new[] { "Robert", "Rudolf", "Anicet" },
            ["04-18"] = new[] { "Bogusława", "Gościsław", "Apolloniusz" },
            ["04-19"] = new[] { "Adolf", "Leon", "Werner" },
            ["04-20"] = new[] { "Czesław", "Agnes", "Teofil" },
            ["04-21"] = new[] { "Anzelm", "Bartosz", "Feliks" },
            ["04-22"] = new[] { "Kajus", "Łukasz", "Soter" },
            ["04-23"] = new[] { "Jerzy", "Wojciech", "Adalbert" },
            ["04-24"] = new[] { "Grzegorz", "Horacy", "Aleksander" },
            ["04-25"] = new[] { "Marek", "Jarosław", "Wasyl" },
            ["04-26"] = new[] { "Maria", "Klaudiusz", "Rychard" },
            ["04-27"] = new[] { "Zyta", "Piotr", "Teofil" },
            ["04-28"] = new[] { "Paweł", "Waleria", "Ludwik" },
            ["04-29"] = new[] { "Piotr", "Katarzyna", "Rita" },
            ["04-30"] = new[] { "Katarzyna", "Marian", "Eutropiusz" },

            // Maj
            ["05-01"] = new[] { "Józef", "Jeremi", "Jakub" },
            ["05-02"] = new[] { "Zygmunt", "Atanazy", "Longina" },
            ["05-03"] = new[] { "Maria", "Mariola", "Aleksander" },
            ["05-04"] = new[] { "Monika", "Florian", "Michał" },
            ["05-05"] = new[] { "Irena", "Waldemar", "Pius" },
            ["05-06"] = new[] { "Judyta", "Filip", "Benedykta" },
            ["05-07"] = new[] { "Gizela", "Benedykt", "Ludmiła" },
            ["05-08"] = new[] { "Stanisław", "Wiktor", "Lidia" },
            ["05-09"] = new[] { "Grzegorz", "Karolina", "Bożydar" },
            ["05-10"] = new[] { "Izydor", "Antonin", "Damian" },
            ["05-11"] = new[] { "Inga", "Ignacy", "Mamert" },
            ["05-12"] = new[] { "Pankracy", "Dominik", "Achilles" },
            ["05-13"] = new[] { "Gloria", "Serwacy", "Robert" },
            ["05-14"] = new[] { "Bonifacy", "Dobiesław", "Maciej" },
            ["05-15"] = new[] { "Zofia", "Izydor", "Jan" },
            ["05-16"] = new[] { "Andrzej", "Szymon", "Jan" },
            ["05-17"] = new[] { "Paschalis", "Weronika", "Bruno" },
            ["05-18"] = new[] { "Eryk", "Feliks", "Jan" },
            ["05-19"] = new[] { "Piotr", "Iwo", "Celestyn" },
            ["05-20"] = new[] { "Bernardyn", "Aleksander", "Bazyli" },
            ["05-21"] = new[] { "Wiktor", "Tymoteusz", "Jan" },
            ["05-22"] = new[] { "Helena", "Julia", "Rita" },
            ["05-23"] = new[] { "Iwona", "Dezydery", "Michał" },
            ["05-24"] = new[] { "Joanna", "Zuzanna", "Wincenty" },
            ["05-25"] = new[] { "Grzegorz", "Urban", "Maria" },
            ["05-26"] = new[] { "Filip", "Paulina", "Ewelina" },
            ["05-27"] = new[] { "Augustyn", "Juliusz", "Jan" },
            ["05-28"] = new[] { "German", "Jaromir", "Wilhelm" },
            ["05-29"] = new[] { "Magdalena", "Teodozja", "Urszula" },
            ["05-30"] = new[] { "Feliks", "Ferdynand", "Joanna" },
            ["05-31"] = new[] { "Aniela", "Petronela", "Kamila" },

            // Czerwiec
            ["06-01"] = new[] { "Justyn", "Konrad", "Jakub" },
            ["06-02"] = new[] { "Marzena", "Marianna", "Erazm" },
            ["06-03"] = new[] { "Leszek", "Tamara", "Klotylda" },
            ["06-04"] = new[] { "Franciszek", "Kwiryna", "Karol" },
            ["06-05"] = new[] { "Bonifacy", "Walter", "Waleriana" },
            ["06-06"] = new[] { "Norbert", "Laurenty", "Paulina" },
            ["06-07"] = new[] { "Robert", "Jarosław", "Wiesław" },
            ["06-08"] = new[] { "Medard", "Wilhelm", "Maksym" },
            ["06-09"] = new[] { "Anna", "Felicjan", "Efrema" },
            ["06-10"] = new[] { "Bogumił", "Diana", "Małgorzata" },
            ["06-11"] = new[] { "Barnaba", "Radomiła", "Feliks" },
            ["06-12"] = new[] { "Janina", "Onufry", "Jan" },
            ["06-13"] = new[] { "Antoni", "Lucjan", "Gracja" },
            ["06-14"] = new[] { "Bazyli", "Eliza", "Waleriusz" },
            ["06-15"] = new[] { "Wit", "Jolanta", "Witomir" },
            ["06-16"] = new[] { "Alina", "Justyna", "Benon" },
            ["06-17"] = new[] { "Albert", "Laura", "Marcjan" },
            ["06-18"] = new[] { "Elżbieta", "Paula", "Marek" },
            ["06-19"] = new[] { "Gerwazy", "Protazy", "Romuald" },
            ["06-20"] = new[] { "Bogna", "Florentyna", "Rafał" },
            ["06-21"] = new[] { "Alicja", "Alojzy", "Rudolf" },
            ["06-22"] = new[] { "Paulina", "Tomasz", "Achacy" },
            ["06-23"] = new[] { "Wanda", "Zenon", "Józef" },
            ["06-24"] = new[] { "Jan", "Danuta", "Janina" },
            ["06-25"] = new[] { "Łucja", "Wilhelm", "Dorota" },
            ["06-26"] = new[] { "Jan", "Paweł", "Dawid" },
            ["06-27"] = new[] { "Władysław", "Cyryl", "Maryla" },
            ["06-28"] = new[] { "Ireneusz", "Leon", "Paweł" },
            ["06-29"] = new[] { "Piotr", "Paweł", "Salomea" },
            ["06-30"] = new[] { "Emilia", "Lucyna", "Marcjal" },

            // Lipiec
            ["07-01"] = new[] { "Halina", "Estera", "Marcin" },
            ["07-02"] = new[] { "Jagoda", "Urban", "Martinion" },
            ["07-03"] = new[] { "Jacek", "Tomasz", "Leon" },
            ["07-04"] = new[] { "Malwina", "Elżbieta", "Zygfryd" },
            ["07-05"] = new[] { "Antoni", "Filomena", "Karolina" },
            ["07-06"] = new[] { "Dominika", "Godelewa", "Maria" },
            ["07-07"] = new[] { "Cyryl", "Metody", "Estera" },
            ["07-08"] = new[] { "Edgar", "Elżbieta", "Eugeniusz" },
            ["07-09"] = new[] { "Lukrecja", "Weronika", "Zenon" },
            ["07-10"] = new[] { "Amelia", "Olaf", "Sylwana" },
            ["07-11"] = new[] { "Benedykt", "Olga", "Kalina" },
            ["07-12"] = new[] { "Jan", "Brunon", "Weronika" },
            ["07-13"] = new[] { "Henryk", "Ernest", "Małgorzata" },
            ["07-14"] = new[] { "Kamil", "Bonawentura", "Ulryk" },
            ["07-15"] = new[] { "Henryk", "Włodzimierz", "Dawid" },
            ["07-16"] = new[] { "Maria", "Stefan", "Eustachy" },
            ["07-17"] = new[] { "Aneta", "Bogdan", "Aleksy" },
            ["07-18"] = new[] { "Emil", "Kamil", "Szymon" },
            ["07-19"] = new[] { "Wincenty", "Arsenius", "Alfred" },
            ["07-20"] = new[] { "Czesław", "Fryderyk", "Małgorzata" },
            ["07-21"] = new[] { "Daniel", "Wiktor", "Laurenty" },
            ["07-22"] = new[] { "Maria", "Magdalena", "Wawrzyniec" },
            ["07-23"] = new[] { "Bogna", "Brygida", "Apolinary" },
            ["07-24"] = new[] { "Kinga", "Krystyna", "Antoni" },
            ["07-25"] = new[] { "Jakub", "Krzysztof", "Walentyna" },
            ["07-26"] = new[] { "Anna", "Joachim", "Mirosław" },
            ["07-27"] = new[] { "Celestyn", "Liliana", "Rudolf" },
            ["07-28"] = new[] { "Wiktor", "Innocenty", "Aida" },
            ["07-29"] = new[] { "Marta", "Olaf", "Beatrycze" },
            ["07-30"] = new[] { "Julita", "Piotr", "Abdon" },
            ["07-31"] = new[] { "Ignacy", "Helena", "Lubomir" },

            // Sierpień
            ["08-01"] = new[] { "Nadieżda", "Justyna", "Nadziei" },
            ["08-02"] = new[] { "Karina", "Gustaw", "Stefan" },
            ["08-03"] = new[] { "Lidia", "August", "Nikodema" },
            ["08-04"] = new[] { "Dominik", "Protazy", "Jan" },
            ["08-05"] = new[] { "Maria", "Oswald", "Karolina" },
            ["08-06"] = new[] { "Jakub", "Felicyta", "Sława" },
            ["08-07"] = new[] { "Kajetan", "Dorota", "Donata" },
            ["08-08"] = new[] { "Cyprian", "Dominik", "Emil" },
            ["08-09"] = new[] { "Roman", "Roland", "Ryszard" },
            ["08-10"] = new[] { "Borys", "Wawrzyniec", "Bożena" },
            ["08-11"] = new[] { "Klara", "Zuzanna", "Ligia" },
            ["08-12"] = new[] { "Hilaria", "Lech", "Innocenty" },
            ["08-13"] = new[] { "Diana", "Hipolit", "Kasjan" },
            ["08-14"] = new[] { "Alfred", "Euzebiusz", "Maksymilian" },
            ["08-15"] = new[] { "Maria", "Stefan", "Napoleon" },
            ["08-16"] = new[] { "Roch", "Joachim", "Stefan" },
            ["08-17"] = new[] { "Jacek", "Żanna", "Anita" },
            ["08-18"] = new[] { "Helena", "Ilona", "Klara" },
            ["08-19"] = new[] { "Jan", "Bolesław", "Ludwik" },
            ["08-20"] = new[] { "Bernard", "Samuel", "Sobiesław" },
            ["08-21"] = new[] { "Franciszka", "Joanna", "Kazimiera" },
            ["08-22"] = new[] { "Cezary", "Mateusz", "Zygfryd" },
            ["08-23"] = new[] { "Apolinary", "Filip", "Róża" },
            ["08-24"] = new[] { "Jerzy", "Bartłomiej", "Emilia" },
            ["08-25"] = new[] { "Ludwik", "Józef", "Patricia" },
            ["08-26"] = new[] { "Maria", "Zefiryn", "Joanna" },
            ["08-27"] = new[] { "Monika", "Józef", "Cezary" },
            ["08-28"] = new[] { "Augustyn", "Adelina", "Aleksy" },
            ["08-29"] = new[] { "Racibor", "Beatrycze", "Jan" },
            ["08-30"] = new[] { "Róża", "Szczęsny", "Rebeka" },
            ["08-31"] = new[] { "Rajmund", "Ramona", "Izabela" },

            // Wrzesień
            ["09-01"] = new[] { "Bronisława", "Idzi", "Konstancja" },
            ["09-02"] = new[] { "Stefan", "Julian", "Teodor" },
            ["09-03"] = new[] { "Izabela", "Grzegorz", "Szymon" },
            ["09-04"] = new[] { "Rozalia", "Róża", "Ida" },
            ["09-05"] = new[] { "Dorota", "Wawrzyniec", "Teresa" },
            ["09-06"] = new[] { "Beata", "Eugeniusz", "Zachariasz" },
            ["09-07"] = new[] { "Melchior", "Regina", "Stefan" },
            ["09-08"] = new[] { "Maria", "Adrianna", "Serafina" },
            ["09-09"] = new[] { "Piotr", "Sergiusz", "Gorgoniusz" },
            ["09-10"] = new[] { "Łukasz", "Mikołaj", "Aldona" },
            ["09-11"] = new[] { "Jacek", "Dagny", "Prot" },
            ["09-12"] = new[] { "Maria", "Gwidon", "Radzimir" },
            ["09-13"] = new[] { "Eugenia", "Aureliusz", "Jan" },
            ["09-14"] = new[] { "Roksana", "Bernard", "Notburga" },
            ["09-15"] = new[] { "Albin", "Albina", "Nikodem" },
            ["09-16"] = new[] { "Edyta", "Korneliusz", "Cyprian" },
            ["09-17"] = new[] { "Franciszka", "Hildegarda", "Robert" },
            ["09-18"] = new[] { "Irma", "Józef", "Stefania" },
            ["09-19"] = new[] { "Konstancja", "January", "Alfred" },
            ["09-20"] = new[] { "Filipina", "Eustachy", "Oleg" },
            ["09-21"] = new[] { "Mateusz", "Jonasz", "Hipolit" },
            ["09-22"] = new[] { "Tomasz", "Maurycy", "Joachim" },
            ["09-23"] = new[] { "Bogusław", "Tekla", "Linus" },
            ["09-24"] = new[] { "Gerard", "Tomira", "Teodor" },
            ["09-25"] = new[] { "Władysław", "Aurelia", "Kleofas" },
            ["09-26"] = new[] { "Justyna", "Cyprian", "Łucja" },
            ["09-27"] = new[] { "Wincenty", "Damian", "Kosma" },
            ["09-28"] = new[] { "Wacław", "Marek", "Lioba" },
            ["09-29"] = new[] { "Michał", "Rafał", "Gabriel" },
            ["09-30"] = new[] { "Wera", "Honoriusz", "Hieronim" },

            // Październik
            ["10-01"] = new[] { "Remigiusz", "Teresa", "Benigna" },
            ["10-02"] = new[] { "Teofil", "Sławomir", "Dionizja" },
            ["10-03"] = new[] { "Teresa", "Heliodor", "Gerard" },
            ["10-04"] = new[] { "Franciszek", "Rozalia", "Edwin" },
            ["10-05"] = new[] { "Justyn", "Flawia", "Placyd" },
            ["10-06"] = new[] { "Artur", "Brunon", "Fryda" },
            ["10-07"] = new[] { "Maria", "Marek", "Justyna" },
            ["10-08"] = new[] { "Pelagia", "Marcin", "Brygida" },
            ["10-09"] = new[] { "Dionizy", "Ludwik", "Arnold" },
            ["10-10"] = new[] { "Franciszek", "Paulina", "Daniel" },
            ["10-11"] = new[] { "Emil", "Aldona", "Dobromiła" },
            ["10-12"] = new[] { "Eustachy", "Edwin", "Maksymilian" },
            ["10-13"] = new[] { "Edward", "Gerald", "Teofil" },
            ["10-14"] = new[] { "Kalikst", "Alan", "Dominik" },
            ["10-15"] = new[] { "Teresa", "Jadwiga", "Aurelia" },
            ["10-16"] = new[] { "Gall", "Florentyna", "Jadwiga" },
            ["10-17"] = new[] { "Ignacy", "Małgorzata", "Wiktor" },
            ["10-18"] = new[] { "Łukasz", "Julian", "Rene" },
            ["10-19"] = new[] { "Piotr", "Jan", "Ziemowit" },
            ["10-20"] = new[] { "Irena", "Kleopatra", "Wendelin" },
            ["10-21"] = new[] { "Urszula", "Celina", "Hilary" },
            ["10-22"] = new[] { "Filip", "Halka", "Kornel" },
            ["10-23"] = new[] { "Seweryn", "Marlena", "Jan" },
            ["10-24"] = new[] { "Rafał", "Antoni", "Marcin" },
            ["10-25"] = new[] { "Daria", "Kryspina", "Wilhelmina" },
            ["10-26"] = new[] { "Ewaryst", "Lucjan", "Damian" },
            ["10-27"] = new[] { "Iwona", "Sabina", "Emilian" },
            ["10-28"] = new[] { "Szymon", "Judyta", "Tadeusz" },
            ["10-29"] = new[] { "Wioletta", "Euzebia", "Felicjan" },
            ["10-30"] = new[] { "Edmund", "Zenobia", "Przemysław" },
            ["10-31"] = new[] { "Urban", "Saturnin", "Wolfgang" },

            // Listopad
            ["11-01"] = new[] { "Seweryn", "Wiktoryna", "Wszystkich Świętych" },
            ["11-02"] = new[] { "Bohdana", "Tobiasz", "Dzień Zaduszny" },
            ["11-03"] = new[] { "Sylwia", "Hubert", "Marcin" },
            ["11-04"] = new[] { "Karol", "Olgierda", "Emeryk" },
            ["11-05"] = new[] { "Elżbieta", "Sławomir", "Zachary" },
            ["11-06"] = new[] { "Leonard", "Feliks", "Leonard" },
            ["11-07"] = new[] { "Antoni", "Żytomir", "Ernest" },
            ["11-08"] = new[] { "Seweryn", "Hadrian", "Gotfryd" },
            ["11-09"] = new[] { "Ursyn", "Teodor", "Ornata" },
            ["11-10"] = new[] { "Leon", "Lena", "Andrzej" },
            ["11-11"] = new[] { "Marcin", "Bartłomiej", "Mennas" },
            ["11-12"] = new[] { "Witold", "Renata", "Jozafat" },
            ["11-13"] = new[] { "Stanisław", "Arkadia", "Mikołaj" },
            ["11-14"] = new[] { "Roger", "Serafina", "Wawrzyniec" },
            ["11-15"] = new[] { "Albert", "Leopold", "Gertruda" },
            ["11-16"] = new[] { "Edmund", "Gertruda", "Małgorzata" },
            ["11-17"] = new[] { "Salomea", "Grzegorz", "Elżbieta" },
            ["11-18"] = new[] { "Aniela", "Klaudyna", "Tomasz" },
            ["11-19"] = new[] { "Elżbieta", "Seweryn", "Paweł" },
            ["11-20"] = new[] { "Feliks", "Anatol", "Edmund" },
            ["11-21"] = new[] { "Janusz", "Konrad", "Albert" },
            ["11-22"] = new[] { "Cecylia", "Marek", "Stefan" },
            ["11-23"] = new[] { "Adela", "Felicyta", "Klemens" },
            ["11-24"] = new[] { "Flora", "Jan", "Emilia" },
            ["11-25"] = new[] { "Katarzyna", "Erazm", "Mojżesz" },
            ["11-26"] = new[] { "Delfina", "Leonard", "Konrad" },
            ["11-27"] = new[] { "Walerian", "Maksymilian", "Wirgiliusz" },
            ["11-28"] = new[] { "Lesław", "Jakub", "Stefana" },
            ["11-29"] = new[] { "Błażej", "Saturnin", "Fryderyk" },
            ["11-30"] = new[] { "Andrzej", "Maura", "Justyna" },

            // Grudzień
            ["12-01"] = new[] { "Natalia", "Eligiusz", "Edmund" },
            ["12-02"] = new[] { "Balbina", "Bibiana", "Paulina" },
            ["12-03"] = new[] { "Franciszek", "Ksawery", "Hilary" },
            ["12-04"] = new[] { "Barbara", "Krystian", "Bernard" },
            ["12-05"] = new[] { "Saba", "Kryspin", "Gerald" },
            ["12-06"] = new[] { "Mikołaj", "Jarema", "Emilian" },
            ["12-07"] = new[] { "Ambroży", "Marcin", "Agata" },
            ["12-08"] = new[] { "Maria", "Światozara", "Zenon" },
            ["12-09"] = new[] { "Wiesław", "Leokadia", "Piotr" },
            ["12-10"] = new[] { "Julia", "Daniela", "Eulalia" },
            ["12-11"] = new[] { "Daniel", "Waldemar", "Damazy" },
            ["12-12"] = new[] { "Joanna", "Aleksandra", "Dagmara" },
            ["12-13"] = new[] { "Łucja", "Otylia", "Jodok" },
            ["12-14"] = new[] { "Alfred", "Izydor", "Jan" },
            ["12-15"] = new[] { "Nina", "Celina", "Walerian" },
            ["12-16"] = new[] { "Albina", "Zdzisława", "Adelajda" },
            ["12-17"] = new[] { "Łazarz", "Jolanta", "Olimpia" },
            ["12-18"] = new[] { "Bogusław", "Gracjan", "Malwin" },
            ["12-19"] = new[] { "Dariusz", "Gabriela", "Urban" },
            ["12-20"] = new[] { "Bogumiła", "Dominik", "Zefiryn" },
            ["12-21"] = new[] { "Tomasz", "Piotr", "Honorata" },
            ["12-22"] = new[] { "Zenon", "Beata", "Franciszka" },
            ["12-23"] = new[] { "Wiktoria", "Sławomira", "Jan" },
            ["12-24"] = new[] { "Adam", "Ewa", "Irmina" },
            ["12-25"] = new[] { "Anastazja", "Eugenia", "Boże Narodzenie" },
            ["12-26"] = new[] { "Szczepan", "Dionizja", "Stefan" },
            ["12-27"] = new[] { "Jan", "Żaneta", "Fabiola" },
            ["12-28"] = new[] { "Antoni", "Teofila", "Cezary" },
            ["12-29"] = new[] { "Tomasz", "Dawid", "Jonasz" },
            ["12-30"] = new[] { "Dawid", "Eugeniusz", "Rajner" },
            ["12-31"] = new[] { "Sylwester", "Melania", "Kolumban" }
        };

        /// <summary>
        /// Pobiera imieniny na dzisiejszy dzień
        /// </summary>
        public static string[] GetTodayNameDays()
        {
            return GetNameDays(DateTime.Now);
        }

        /// <summary>
        /// Pobiera imieniny na podaną datę
        /// </summary>
        public static string[] GetNameDays(DateTime date)
        {
            string key = date.ToString("MM-dd");
            if (NameDays.TryGetValue(key, out var names))
            {
                return names;
            }
            return new string[0];
        }

        /// <summary>
        /// Pobiera sformatowany tekst imienin na dziś
        /// </summary>
        public static string GetTodayNameDaysText()
        {
            var names = GetTodayNameDays();
            if (names.Length == 0)
                return "";
            return string.Join(", ", names);
        }

        /// <summary>
        /// Pobiera pełny tekst z nagłówkiem
        /// </summary>
        public static string GetTodayNameDaysWithHeader()
        {
            var names = GetTodayNameDays();
            if (names.Length == 0)
                return "Imieniny: brak danych";
            return $"Imieniny: {string.Join(", ", names)}";
        }
    }
}
